name: p1

on:
  workflow_dispatch: 
    inputs:
      name:
        default: 'john'
        description: 'name of the person'
        type: string
        required: true
        options:
          - 'Joe'
          - 'Amy'

concurrency: 
  cancel-in-progress: false
  group: 'p1-group'
  queue: max

description: 'p1 pipeline'
run-name: ${{ github.ref_name }} - Run

env:
  AWS_REGION: us-east-1
  ENVIRONMENT: dev

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
  greet:
    runs_on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v7
        with:
          ref: "dev"
      
  





